-- create table users
-- (
--     username varchar_ignorecase(50)  not null,
--     password varchar_ignorecase(500) not null,
--     enabled  boolean                 not null default true,
--     primary key (username)
-- );
--
-- create table authorities
-- (
--     username  varchar_ignorecase(50) not null,
--     authority varchar_ignorecase(50) not null,
--     constraint fk_authorities_users foreign key (username) references users (username)
-- );
-- create unique index ix_auth_username on authorities (username, authority);

create table Users
(
    id       integer generated by default as identity,
    username varchar_ignorecase(50)  not null,
    password varchar_ignorecase(500) not null,
    primary key (id)
);

create table Authorities
(
    id        integer generated by default as identity,
    username  varchar_ignorecase(50) not null,
    authority varchar_ignorecase(50) not null,
    primary key (id),
    constraint fk_authorities_users foreign key (id) references users (id)
);
create unique index ix_auth_username on Authorities (username, authority);

create table Paintings
(
    id          integer generated by default as identity,
    title       varchar(200)  not null,
    published   date          not null,
    imagePath   varchar(700)  not null,
    size        varchar(255)  not null,
    material    varchar(255)  not null,
    description varchar(2000) not null,
    price       decimal(7, 2) not null,
    primary key (id)
);

create table Categories
(
    id   integer generated by default as identity,
    name varchar(255) unique,
    primary key (id)
);

create table Authors
(
    id        integer generated by default as identity,
    pseudonym varchar(255)  not null,
    firstName varchar(255)  not null,
    surname   varchar(255)  not null,
    birthDate date          not null,
    awards    varchar(2000) not null,
    imagePath varchar(700)  not null,
    primary key (id)
);

create table Comments
(
    id      integer generated by default as identity,
    content varchar(1000) not null,
    primary key (id)
);

create table Auctions
(
    id            integer generated by default as identity,
    title         varchar(255)  not null,
    published     date          not null,
    startingPrice decimal(7, 2) not null,
    currentPrice  decimal(7, 2) not null,
    deadline      date          not null,
    winner        varchar(255),
    primary key (id)
);
