GET http://localhost:8080/adminPageAuction/api/v2/auctions
Accept: application/json

###
GET http://localhost:8080/adminPageAuction/api/v2/auctions/1
Accept: application/json

###
POST http://localhost:8080/adminPageAuction/api/v2/auctions
Content-Type: application/json

{
  "titleAuction":"New Auction",
  "startDate": "2022-12-28",
  "endDate": "2023-01-01",
  "startingPrice": "2000",
  "active": "false"

}

###
PUT http://localhost:8080/adminPageAuction/api/v2/auctions/3
Content-Type: application/json

{
  "titleAuction":"New Auction",
  "startDate": "2022-12-28",
  "endDate": "2023-01-01",
  "startingPrice": "2000",
  "active": "false"

}

###
DELETE http://localhost:8080/adminPageAuction/api/v2/auctions/3
