GET http://localhost:8080/adminPageUsers/api/v3/users
Accept: application/json

###
GET http://localhost:8080/adminPageUsers/api/v3/users/2
Accept: application/json

###
POST http://localhost:8080/adminPageUsers/api/v3/users
Content-Type: application/json

{
  "username":"Alina",
  "password": "1111",
  "enabled": "true"

}

###
PUT http://localhost:8080/adminPageUsers/api/v3/users/4
Content-Type: application/json

{
  "username":"Alina",
  "password": "1111",
  "enabled": "true"

}

###
DELETE http://localhost:8080/adminPageUsers/api/v3/users/4
